[app]

GOOGLE_API_KEY= 'AQ.Ab8RN6J8YFWC-VHuYPicoXUovAwJ0q5-d2c7YpMVPfvQ8d4X5A'

MONGODB_URI= 'mongodb+srv://adr123:adr123adr123@ab.zurijzi.mongodb.net/'

COHERE_API_KEY= 'bzUYUpkTzgXtcdeB3pgY7TAiFm7qgxgG335H5K1g'

USER = 'adrianlozano'
